title: Home
email: andrecogno@hotmail.it
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mrandri19.github.io"
github_username: mrandri19
google_analytics: G-FBTQYT7Z06
description: "my blog"

# Build settings
markdown: kramdown
theme: minima
header_pages:
  - blog.md
